development:
  adapter: redshift
  host: nci-test.coc6hp4nwupw.us-east-1.redshift.amazonaws.com
  port: 5439
  database: dev
  username: awsuser
  password: Rabc123*
  encoding: utf8
  pool: 3
  timeout: 5000
